const translations = {
    en: {
        general: {
            title: "Welcome",
            subtitle: "Discover my work and services",
            "intro-text1": "As a Trade Marketing professional, I have experience with POS materials, product launches, events, and training, working within teams in large companies to enhance brand presence and market impact.",
            "intro-text2": "As a freelancer, I focus on content creation for clients, developing strategies for social media, designing websites, and crafting HTML-based resumes. I also explore creativity through handmade crafts, bringing unique and personalized designs to life.",
            "intro-text3": "I’m passionate about creating—whether it’s digital content, marketing materials, or handcrafted pieces. I enjoy organizing presentations, structuring ideas, and transforming concepts into engaging experiences."
        },
        projects: {
            "proj1-title": "Little Loops Crafts",
            "proj1-role": "2025 – Freelancer",
            "proj1-desc": "Developed as part of a learning journey in HTML, CSS, and JavaScript, this project showcased handcrafted products from the brand Little Loops Crafts. The page was fully designed and coded to present amigurumi, crochet, and other handmade items, focusing on visual identity, responsive layout, and product display. It also included light JavaScript interactions to enhance the user experience, combining technical practice with the goal of promoting the brand’s artisanal creations.",
            "proj2-title": "Müller Informática",
            "proj2-role": "2025 – Freelancer",
            "proj2-desc": "Responsible for the creation and execution of the social media content strategy for a computer store that offers hardware sales and technical services for computers and printers. Activities included planning and managing the editorial calendar, writing copy, and designing all posts using Canva. Oversaw the entire process — from concept development to visual creation and publication — ensuring consistent communication aligned with the client’s brand and business goals.",
            "proj3-title": "Müller Informática",
            "proj3-role": "2023 – Freelancer",
            "proj3-desc": "Responsible for designing and developing a responsive website for a computer store specialized in hardware sales and technical support for computers and printers. The project was built using HTML and CSS, focusing on clean layout, user-friendly navigation, and clear presentation of services. The goal was to strengthen the store’s digital presence and facilitate access to essential information for customers.",
            "proj4-title": "Germany Bits",
            "proj4-role": "Hobby",
            "proj4-desc": "Exploring a new country is a journey full of discoveries! On thi page, I share curiosities and interesting insights about Germany - things I come across during my readings, daily life, and travels. From history and traditions to modern-day quirks, this is my way of documenting and sharing what I learn about the country I now call home.",
            "proj5-title": "Shipping Summit",
            "proj5-role": "2024 – Freelancer",
            "proj5-desc": "Led the strategic planning of digital content for the first Shipping Summit held in São Paulo — a pioneering event in the sector and a notable success in terms of audience and engagement. Responsibilities included developing the editorial calendar, creating social media copy, coordinating with the designer for the production of visual assets, and managing communication with the client to align and approve all materials. Ensured that all content was delivered and published according to the established schedule.",
            "proj6-title": "Escola Wilma Kövesi de Cozinha",
            "proj6-role": "2024/25 - Freelancer",
            "proj6-desc": "Developed the digital content strategy for WK Cozinha, a culinary school catering to all levels — from beginners to professionals. Activities included building the editorial calendar, writing engaging content for social media and newsletters, and working closely with the designer to create visuals that reflected the brand’s educational tone. Managed the full approval workflow with the client, aligning communication with course offerings and seasonal themes.",
            "proj7-title": "Arotec",
            "proj7-role": "2023/24/25 - Freelancer",
            "proj7-desc": "Led content strategy for Arotec’s LinkedIn presence — a company with 50 years of tradition representing brands like Struers, Foerster, and Evident in Brazil. Focused on producing technical and institutional content tailored to the B2B audience. Responsibilities included creating the editorial calendar, writing copy aligned with industry trends and product innovations, coordinating visual materials with the designer, and ensuring client approvals followed communication standards and technical accuracy.",
            "proj8-title": "Zulcare",
            "proj8-role": "2024/25 - Freelancer",
            "proj8-desc": "Responsible for planning and producing content for Zulcare, a store and artisanal sweets kitchen. Created the editorial calendar, wrote content that emphasized natural ingredients and handcrafted techniques, and coordinated with the designer for visuals that captured the brand’s sensorial and emotional appeal. Led client alignment and approval to ensure consistent messaging and seasonal highlights.",
            "proj9-title": "Lig Veículos",
            "proj9-role": "2023/24/25 - Freelancer",
            "proj9-desc": "Developed the social media content strategy for LigVeículos, a leading company in electric vehicle sales, rentals, and maintenance in Brazil. Responsibilities included organizing the editorial calendar, creating educational and promotional content, and mediating between the designer and client during the creative and approval stages. The goal was to position the brand as a sustainable and innovative mobility reference.",
            "proj10-title": "Mesa III - Pastifício",
            "proj10-role": "2023/24 - Freelancer",
            "proj10-desc": "Responsible for structuring the content planning and execution for Mesa3, a handmade pasta shop led by chef Ana Soares. The role included crafting the editorial calendar, writing engaging and product-centered content, and coordinating visuals with the designer. Maintained close contact with the client to review and approve creative materials that highlighted the artisanal and exclusive nature of the brand.",
            "proj11-title": "Ice4Pros",
            "proj11-role": "2023/24 - Freelancer",
            "proj11-desc": "Responsible for developing and managing the content strategy for Ice4Pros, a brand that brought innovation to Brazil’s cocktail market through perfectly crafted, clear, and standardized ice. Activities included planning the editorial calendar, writing content for social media, and coordinating with the designer for creative asset production. Served as the bridge between creative deliveries and client approvals, ensuring alignment with the brand's sophisticated positioning.",
            "proj12-title": "Kssara",
            "proj12-role": "2023 - Freelancer",
            "proj12-desc": "Led the development of the social media content strategy for Emporio Kssara, a Middle Eastern gourmet market in São Paulo offering nuts, imported goods, and beverages. Tasks involved creating the editorial calendar, writing product-focused content, coordinating with the designer for visual arts creation, and managing client approval to ensure effective and timely communication.",
            "proj13-title": "Carnes del Sur",
            "proj13-role": "2023 - Freelancer",
            "proj13-desc": "Responsible for planning and executing the content strategy for Carnes del Sur, a butcher shop specializing in premium cuts for barbecues and everyday meals. Duties included creating the editorial calendar, writing posts that connected with meat lovers and grill enthusiasts, aligning creative materials with the designer, and leading the approval process with the client to maintain consistency and timely delivery.",
            "proj14-title": "Amazon",
            "proj14-role": "Alexa Smart Home Table",
            "proj14-desc": "Led the development and implementation of the new Alexa display table at Fast Shop, featuring an integrated smart home model to enhance product storytelling and shopper engagement. Managed the full process — from briefing and creative alignment with the agency to supplier coordination and retail negotiation. The concept introduced a premium layout with ambient lighting, natural finishes, and an immersive demonstration of connected devices within a simulated home environment.",
            "proj15-title": "Amazon",
            "proj15-role": "Echo Display Revamp",
            "proj15-desc": "Led the end-to-end process for the implementation of a new display concept for Amazon Echo devices — from briefing and alignment with the creative agency to supplier coordination and retail negotiations for in-store rollout. The new design delivered a cleaner aesthetic, integrated lighting, natural textures, and improved product segmentation, resulting in a more premium and intuitive shopper experience.",
            "proj16-title": "Amazon",
            "proj16-role": "Alexa Table",
            "proj16-desc": "Coordinated the update of the Amazon Table to enhance shopper experience at the point of sale. The project focused on reorganizing product layout and improving visual communication to highlight key features and interactions of the Alexa ecosystem. Ensured alignment between internal teams, retail partners, and production suppliers to deliver a clean, intuitive, and brand-consistent experience at the POS.",
            "proj17-title": "Ferrero",
            "proj17-role": "Kids Day",
            "proj17-desc": "Led the development of POS materials and in-store activations for the Children's Day campaign, combining Kinder and Nutella product lines. The initiative included the creation of themed displays — such as the Kinder train — and coordination with creative agencies and suppliers to bring playful, high-impact visibility to the point of sale. Managed the full process from briefing to rollout, reinforcing brand presence and engagement during a key seasonal period.",
            "proj18-title": "Ferrero",
            "proj18-role": "Nutella",
            "proj18-desc": "Supported the development and implementation of the Pão na Chapa com Nutella concept in bakeries across Brazil — inspired by the insight that “Brazilian breakfast out of home is pão na chapa… so why not with Nutella?” Oversaw the creation of promotional materials for in-store communication and coordinated local tasting activations to drive visibility, trial, and adoption of the initiative.",
            "proj19-title": "Ferrero",
            "proj19-role": "Visibility",
            "proj19-desc": "Supported the development of key materials for the Easter campaign, including POS displays, product catalogs, and execution guides. Assisted in managing production, tracking deliveries, and organizing the distribution of materials to the merchandising team to ensure proper implementation at the point of sale.",
            "proj20-title": "Mead Johnson",
            "proj20-role": "Sustagen Nutriferro Farma Launch",
            "proj20-desc": "Contributed to the launch of Sustagem Nutriferro by developing and negotiating the installation of branded mini-fridges in select drugstores — an uncommon resource in this retail environment. The initiative aimed to offer the product refrigerated for on-the-go consumption, enhancing visibility and requiring close coordination with commercial teams and retailer networks.",
            "proj21-title": "Mead Johnson",
            "proj21-role": "Sustagen Category",
            "proj21-desc": "Developed a custom display unit (island format) to enhance the in-store presence of Sustagen in supermarkets. The project focused on creating a new POS material format to improve product visibility, facilitate replenishment, and attract consumer attention at the point of sale. Involved material planning, alignment with suppliers, and coordination with commercial teams to ensure rollout in key high-traffic stores.",
            "proj22-title": "Mead Johnson",
            "proj22-role": "Sustagen Category",
            "proj22-desc": "Coordinated the development of point-of-sale materials for the launch of Sustagen Nutriferro. Led the briefing process and worked closely with creative agencies on the design of a complete POS kit, aimed at driving visibility and conversion. Managed production alignment with suppliers to ensure execution quality and timely delivery to key retail partners.",
        },
    },

    de: {
        general: {
            title: "Willkommen",
            subtitle: "Entdecken Sie meine Arbeit und Dienstleistungen",
            "intro-text1": "Als Fachfrau für Handelsmarketing habe ich Erfahrung mit POS-Materialien, Produkteinführungen, Veranstaltungen und Schulungen und arbeite in Teams großer Unternehmen, um die Markenpräsenz und Marktwirkung zu verbessern.",
            "intro-text2": "Als Freiberuflerin konzentriere ich mich auf die Erstellung von Inhalten für Kunden, die Entwicklung von Strategien für soziale Medien, die Gestaltung von Websites und die Erstellung von HTML-basierten Lebensläufen. Außerdem erforsche ich meine Kreativität durch handgefertigte Kunstwerke und erwecke einzigartige und persönliche Designs zum Leben.",
            "intro-text3": "Ich habe eine Leidenschaft für die Erstellung von digitalen Inhalten, Marketingmaterialien oder handgefertigten Stücken. Es macht mir Spaß, Präsentationen zu organisieren, Ideen zu strukturieren und Konzepte in ansprechende Erlebnisse zu verwandeln."

        },
        projects: {
            "proj1-title": "Little Loops Crafts",
            "proj1-role": "2025 – Freelancer",
            "proj1-desc": "Dieses Projekt wurde als Teil einer Lernreise in HTML, CSS und JavaScript entwickelt und stellte handgefertigte Produkte der Marke Little Loops Crafts vor. Die Seite wurde vollständig entworfen und kodiert, um Amigurumi, Häkelarbeiten und andere handgefertigte Produkte zu präsentieren, wobei der Schwerpunkt auf visueller Identität, responsivem Layout und Produktdarstellung lag. Die Seite enthielt auch leichte JavaScript-Interaktionen, um das Benutzererlebnis zu verbessern, und kombinierte technische Verfahren mit dem Ziel, die handwerklichen Kreationen der Marke zu fördern.",
            "proj2-title": "Müller Informática",
            "proj2-role": "2025 – Freelancer",
            "proj2-desc": "Verantwortlich für die Erstellung und Umsetzung der Social-Media-Inhaltsstrategie für einen Computerladen, der Hardware-Verkauf und technische Dienstleistungen für Computer und Drucker anbietet. Zu den Tätigkeiten gehörten die Planung und Verwaltung des Redaktionskalenders, das Schreiben von Texten und die Gestaltung aller Beiträge mit Canva. Überwachung des gesamten Prozesses - von der Erstellung des Designs über die visuelle Gestaltung bis hin zur Publikation - und Sicherstellung einer konsistenten Kommunikation im Einklang mit der Marke und den Geschäftszielen des Kunden.",
            "proj3-title": "Müller Informática",
            "proj3-role": "2023 – Freelancer",
            "proj3-desc": "Verantwortlich für die Gestaltung und Entwicklung einer responsiven Website für einen Computerladen, der sich auf den Verkauf von Hardware und den technischen Support für Computer und Drucker spezialisert ist. Das Projekt wurde mit HTML und CSS erstellt, mit Fokus auf ein sauberes Layout, eine benutzerfreundliche Navigation und eine klare Präsentation der Dienstleistungen. Ziel war es, die digitale Präsenz des Geschäfts zu stärken und den Zugang zu wichtigen Informationen für die Kunden zu erleichtern.",
            "proj4-title": "Germany Bits",
            "proj4-role": "Hobby",
            "proj4-desc": "Die Erkundung eines neuen Landes ist eine Reise voller Entdeckungen! Auf dieser Seite teile ich Kuriositäten und interessante Erkenntnisse über Deutschland - Dinge, auf die ich beim Lesen, im täglichen Leben und auf Reisen stoße. Von der Geschichte und den Traditionen bis hin zu modernen Eigenheiten - dies ist meine Art, zu dokumentieren und zu teilen, was ich über das Land erfahre, das ich jetzt mein Zuhause nenne.",
            "proj5-title": "Shipping Summit",
            "proj5-role": "2024 – Freelancer",
            "proj5-desc": "Leitung der strategischen Planung digitaler Inhalte für den ersten Shipping Summit in São Paulo - eine Pionierveranstaltung in diesem Sektor und ein bemerkenswerter Erfolg in Bezug auf Publikum und Engagement. Zu den Aufgaben gehörten die Entwicklung des Redaktionskalenders, die Erstellung von Texten für soziale Medien, die Koordination mit dem Designer für die Produktion visueller Assets und die Verwaltung der Kommunikation mit dem Kunden, um alle Materialien abzustimmen und zu genehmigen. Es wurde sichergestellt, dass alle Inhalte gemäß dem festgelegten Zeitplan geliefert und veröffentlicht wurden.",
            "proj6-title": "Escola Wilma Kövesi de Cozinha",
            "proj6-role": "2024/25 - Freelancer",
            "proj6-desc": "Entwicklung der Strategie für digitale Inhalte für WK Cozinha, eine Kochschule, die sich an alle Niveaus richtet - vom Anfänger bis zum Profi. Zu den Aktivitäten gehörten die Erstellung des Redaktionskalenders, das Verfassen ansprechender Inhalte für soziale Medien und Newsletter sowie die enge Zusammenarbeit mit dem Designer, um visuelle Inhalte zu erstellen, die den pädagogischen Ansatz der Marke widerspiegeln. Management des gesamten Genehmigungs-Workflows mit dem Kunden, Anpassung der Kommunikation an Kursangebote und saisonale Themen.",
            "proj7-title": "Arotec",
            "proj7-role": "2023/24/25 - Freelancer",
            "proj7-desc": "Leitung der Content-Strategie für die LinkedIn-Präsenz von Arotec - einem Unternehmen mit 50-jähriger Tradition, das Marken wie Struers, Foerster und Evident in Brasilien repräsentiert. Der Schwerpunkt lag auf der Erstellung technischer und institutioneller Inhalte, die auf das B2B-Publikum zugeschnitten sind. Die Aufgaben umfassten die Erstellung des Redaktionskalenders, das Verfassen von Texten, die sich an Branchentrends und Produktinnovationen orientieren, die Koordinierung von visuellem Material mit dem Designer und die Sicherstellung der Genehmigung durch den Kunden unter Einhaltung von Kommunikationsstandards und technischer Genauigkeit.",
            "proj8-title": "Zulcare",
            "proj8-role": "2024/25 - Freelancer",
            "proj8-desc": "Verantwortlich für die Planung und Produktion von Inhalten für Zulcare, ein Geschäft und eine handwerkliche Süßwarenküche. Erstellung des Redaktionskalenders, Verfassen von Inhalten, die natürliche Zutaten und handwerkliche Techniken betonen, und Abstimmung mit dem Designer für visuelle Inhalte, die den sensorischen und emotionalen Reiz der Marke einfangen. Koordination und Genehmigung mit dem Kunden, um ein einheitliches Messaging und saisonale Highlights zu gewährleisten.",
            "proj9-title": "Lig Veículos",
            "proj9-role": "2023/24/25 - Freelancer",
            "proj9-desc": "Entwicklung der Social-Media-Inhaltsstrategie für LigVeículos, ein führendes Unternehmen für den Verkauf, die Vermietung und die Wartung von Elektrofahrzeugen in Brasilien. Zu den Aufgaben gehörte die Organisation des Redaktionskalenders, die Erstellung von Lehr- und Werbeinhalten und die Vermittlung zwischen dem Designer und dem Kunden während der Kreativ- und Genehmigungsphase. Ziel war es, die Marke als nachhaltige und innovative Mobilitätsreferenz zu positionieren.",
            "proj10-title": "Mesa III - Pastifício",
            "proj10-role": "2023/24 - Freelancer",
            "proj10-desc": "Verantwortlich für die Strukturierung der Inhaltsplanung und Umsetzung für Mesa3, einen Laden für handgemachte Pasta, der von der Chefköchin Ana Soares geführt wird. Die Aufgabe umfasste die Erstellung des Redaktionskalenders, das Verfassen ansprechender und produktbezogener Inhalte und die Abstimmung des Bildmaterials mit dem Designer. Enger Kontakt mit dem Kunden, um kreative Materialien zu prüfen und zu genehmigen, die den handwerklichen und exklusiven Charakter der Marke hervorheben.",
            "proj11-title": "Ice4Pros",
            "proj11-role": "2023/24 - Freelancer",
            "proj11-desc": "Verantwortlich für die Entwicklung und Verwaltung der Content-Strategie für Ice4Pros, eine Marke, die den brasilianischen Cocktailmarkt durch perfekt hergestelltes, klares und standardisiertes Eis innovativ machte. Zu den Aktivitäten gehörten die Planung des Redaktionskalenders, das Schreiben von Inhalten für soziale Medien und die Koordination mit dem Designer für die Produktion kreativer Inhalte. Diente als Brücke zwischen den kreativen Lieferungen und den Kundenfreigaben und sorgte für die Abstimmung mit der anspruchsvollen Positionierung der Marke.",
            "proj12-title": "Kssara",
            "proj12-role": "2023 - Freelancer",
            "proj12-desc": "Leitete die Entwicklung der Social-Media-Inhaltsstrategie für Emporio Kssara, einen Gourmetmarkt in São Paulo, der Nüsse, importierte Waren und Getränke anbietet. Zu den Aufgaben gehörten die Erstellung des Redaktionskalenders, das Verfassen produktbezogener Inhalte, die Koordination mit dem Designer für die Erstellung der visuellen Inhalte und die Verwaltung der Kundenfreigabe, um eine effektive und zeitnahe Kommunikation zu gewährleisten.",
            "proj13-title": "Carnes del Sur",
            "proj13-role": "2023 - Freelancer",
            "proj13-desc": "Verantwortlich für die Planung und Umsetzung der Content-Strategie für Carnes del Sur, eine Metzgerei, die sich auf hochwertige Fleischstücke für Grillpartys und Alltagsgerichte spezialisiert hat. Zu den Aufgaben gehörte die Erstellung des Redaktionskalenders, das Verfassen von Beiträgen, die Fleischliebhaber und Grillfans ansprechen, die Abstimmung der kreativen Materialien mit dem Designer und die Leitung des Genehmigungsprozesses mit dem Kunden, um die Übereinstimmung mit der Geschäftsstrategie zu gewährleisten.",
            "proj14-title": "Amazon",
            "proj14-role": "Alexa Smart Home Table",
            "proj14-desc": "Leitete die Entwicklung und Umsetzung des neuen Alexa-Display-Tisches bei Fast Shop, der ein integriertes Smart-Home-Modell enthält, um die Produktpräsentation und die Kundenbindung zu verbessern. Steuerung des gesamten Prozesses - vom Briefing und der kreativen Abstimmung mit der Agentur bis hin zur Koordination der Dienstleister und der Verhandlung mit dem Einzelhandel. Das Konzept umfasste ein hochwertiges Layout mit Umgebungsbeleuchtung, natürlichen Oberflächen und einer eindrucksvollen Demonstration von vernetzten Geräten in einer simulierten Wohnumgebung.",
            "proj15-title": "Amazon",
            "proj15-role": "Echo Display Revamp",
            "proj15-desc": "Leitete den End-to-End-Prozess für die Umsetzung eines neuen Display-Konzepts für Amazon Echo-Geräte - vom Briefing und der Abstimmung mit der Kreativagentur bis hin zur Koordination der Hersteller und Verhandlungen mit dem Einzelhandel für die Einführung in den Stores. Das neue Design zeichnet sich durch eine klarere Ästhetik, integrierte Beleuchtung, natürliche Texturen und eine verbesserte Produktsegmentierung aus, was zu einem hochwertigeren und intuitiveren Einkaufserlebnis führt.",
            "proj16-title": "Amazon",
            "proj16-role": "Alexa Table",
            "proj16-desc": "Koordinierte die Aktualisierung des Amazon Table, um das Einkaufserlebnis am Point of Sale zu verbessern. Das Projekt konzentrierte sich auf die Umstrukturierung des Produktlayouts und die Verbesserung der visuellen Kommunikation, um die wichtigsten Funktionen und Interaktionen des Alexa-Ökosystems hervorzuheben. Sicherstellung der Abstimmung zwischen internen Teams, Einzelhandelspartnern und Produktionslieferanten, um ein sauberes, intuitives und markenkonsistentes Erlebnis am POS zu schaffen.",
            "proj17-title": "Ferrero",
            "proj17-role": "Kids Day",
            "proj17-desc": "Entwicklung von POS-Materialien und In-Store-Aktivierungen für die Kindertagskampagne, die die Produktlinien Kinder und Nutella kombinierte. Die Initiative umfasste die Gestaltung von Themen-Displays - wie z. B. der Kinder-Eisenbahn - und die Koordination mit Kreativagenturen und Dienstleistern, um eine spielerische, aufmerksamkeitsstarke Sichtbarkeit am Point of Sale zu erreichen. Management des gesamten Prozesses vom Briefing bis zum Rollout, Stärkung der Markenpräsenz und des Engagements während einer wichtigen Saisonperiode.",
            "proj18-title": "Ferrero",
            "proj18-role": "Nutella",
            "proj18-desc": "Unterstützte die Entwicklung und Umsetzung des Konzepts Pão na Chapa com Nutella in Bäckereien in ganz Brasilien - inspiriert von der Erkenntnis: „Das brasilianische Frühstück außer Haus ist Pão na Chapa... warum also nicht mit Nutella?“ Überwachung der Erstellung von Werbematerialien für die Kommunikation in den Geschäften und Koordinierung lokaler Verkostungsaktionen, um die Sichtbarkeit, das Probieren und die Akzeptanz der Initiative zu fördern.",
            "proj19-title": "Ferrero",
            "proj19-role": "Visibility",
            "proj19-desc": "Unterstützung bei der Entwicklung von Schlüsselmaterialien für die Osterkampagne, einschließlich POS-Displays, Produktkatalogen und Ausführungsanleitungen. Begleitung der Produktion, Überwachung der Lieferungen und Organisation der Verteilung der Materialien an das Merchandising-Team, um eine ordnungsgemäße Umsetzung am Point of Sale zu gewährleisten.",
            "proj20-title": "Mead Johnson",
            "proj20-role": "Sustagen Nutriferro Farma Launch",
            "proj20-desc": "Beitrag zur Markteinführung von Sustagem Nutriferro durch die Entwicklung und Verhandlung der Installation von Mini-Kühlschränken der Marke in ausgewählten Drogerien - eine ungewöhnliche Ressource in diesem Einzelhandelsumfeld. Die Initiative zielte darauf ab, das Produkt gekühlt für den Verzehr unterwegs anzubieten, was die Sichtbarkeit erhöhte und eine enge Abstimmung mit den Handelsteams und Einzelhändlernetzen erforderte.",
            "proj21-title": "Mead Johnson",
            "proj21-role": "Sustagen Category",
            "proj21-desc": "Entwicklung einer maßgeschneiderten Präsentationseinheit zur Verbesserung der Präsenz von Sustagen in Supermärkten. Das Projekt konzentrierte sich auf die Entwicklung eines neuen POS-Materialformats, um die Sichtbarkeit der Produkte zu verbessern, den Warennachschub zu erleichtern und die Aufmerksamkeit der Kunden am Point of Sale zu gewinnen. Das Projekt umfasste die Materialplanung, die Abstimmung mit den Herstellern und die Koordinierung mit den Handelsteams, um die Einführung in wichtigen, stark frequentierten Geschäften sicherzustellen.",
            "proj22-title": "Mead Johnson",
            "proj22-role": "Sustagen Category",
            "proj22-desc": "Koordinierte die Entwicklung von Point-of-Sale-Materialien für die Einführung von Sustagen Nutriferro. Leitung des Briefing-Prozesses und enge Zusammenarbeit mit Kreativagenturen bei der Gestaltung eines kompletten POS-Kits, das die Sichtbarkeit und den Umsatz steigern soll. Koordination der Produktion mit den Herstellern, um die Qualität der Ausführung und die rechtzeitige Lieferung an die wichtigsten Einzelhandelspartner zu gewährleisten.,"
        },
        footer: {
            contact: "Kontakt",
            rights: "Alle Rechte vorbehalten."
        }
    },

    pt: {
        general: {
            title: "Bem-vindo",
            subtitle: "Descubra meu trabalho e serviços",
            "intro-text1": "Como profissional de Trade Marketing, tenho experiência com materiais de PDV, lançamentos de produtos, eventos e treinamento, trabalhando em equipes de grandes empresas para melhorar a presença da marca e o impacto no mercado.",
            "intro-text2": "Como freelancer, concentro-me na criação de conteúdo para clientes, desenvolvendo estratégias para mídias sociais, projetando sites e elaborando currículos baseados em HTML. Também exploro a criatividade por meio de artesanato, dando vida a designs exclusivos e personalizados.",
            "intro-text3": "Sou apaixonada por criar, seja conteúdo digital, materiais de marketing ou peças artesanais. Gosto de organizar apresentações, estruturar ideias e transformar conceitos em experiências envolventes."
        },
        projects: {
            "proj1-title": "Little Loops Crafts",
            "proj1-role": "2025 – Freelancer",
            "proj1-desc": "Desenvolvido como parte de uma jornada de aprendizado em HTML, CSS e JavaScript, esse projeto apresenta produtos artesanais da marca Little Loops Crafts. A página foi totalmente projetada e codificada para apresentar amigurumi, crochê e outros itens feitos à mão, com foco em identidade visual, layout responsivo e exibição de produtos. Também incluiu interações leves em JavaScript para aprimorar a experiência do usuário, combinando a prática técnica com o objetivo de promover as criações artesanais da marca.",
            "proj2-title": "Müller Informática",
            "proj2-role": "2025 – Freelancer",
            "proj2-desc": "Responsável pela criação e execução da estratégia de conteúdo de mídia social para uma loja de informática que oferece vendas de hardware e serviços técnicos para computadores e impressoras. As atividades incluíram o planejamento e o gerenciamento do calendário editorial, a redação de textos e o design de todas as postagens usando o Canva. Supervisionei todo o processo, desde o desenvolvimento do conceito até a criação visual e a publicação, garantindo uma comunicação consistente e alinhada com a marca e as metas comerciais do cliente.",
            "proj3-title": "Müller Informática",
            "proj3-role": "2023 – Freelancer",
            "proj3-desc": "Responsável pelo projeto e desenvolvimento de um site responsivo para uma loja de informática especializada em vendas de hardware e suporte técnico para computadores e impressoras. O projeto foi criado usando HTML e CSS, com foco em um layout limpo, navegação fácil de usar e apresentação clara dos serviços. O objetivo era fortalecer a presença digital da loja e facilitar o acesso dos clientes a informações essenciais.",
            "proj4-title": "Germany Bits",
            "proj4-role": "Hobby",
            "proj4-desc": "Explorar um novo país é uma jornada cheia de descobertas! Nesta página, compartilho curiosidades e percepções interessantes sobre a Alemanha - coisas que encontro durante minhas leituras, vida cotidiana e viagens. Desde a história e as tradições até as peculiaridades dos dias atuais, esta é a minha maneira de documentar e compartilhar o que aprendo sobre o país que agora chamo de lar.",
            "proj5-title": "Shipping Summit",
            "proj5-role": "2024 – Freelancer",
            "proj5-desc": "Liderar o planejamento estratégico de conteúdo digital para o primeiro Shipping Summit realizado em São Paulo - um evento pioneiro no setor e um sucesso notável em termos de público e engajamento. As responsabilidades incluíram o desenvolvimento do calendário editorial, a criação de textos para mídias sociais, a coordenação com o designer para a produção de recursos visuais e o gerenciamento da comunicação com o cliente para alinhar e aprovar todos os materiais. Além do acompanhamento para publicação do conteúdo de acordo com o cronograma estabelecido.",
            "proj6-title": "Escola Wilma Kövesi de Cozinha",
            "proj6-role": "2024/25 - Freelancer",
            "proj6-desc": "Desenvolvimeto da estratégia de conteúdo digital para a WK Cozinha, uma escola de culinária que atende a todos os níveis, de iniciantes a profissionais. As atividades incluíram a criação do calendário editorial, a redação de conteúdo para mídias sociais e newsletters. Trabalho em conjunto com o designer para criar artes que refletissem o tom educacional da marca. Gerenciamento de todo o fluxo de aprovação com o cliente, alinhando a comunicação com as ofertas de cursos e temas sazonais.",
            "proj7-title": "Arotec",
            "proj7-role": "2023/24/25 - Freelancer",
            "proj7-desc": "Responsável pela estratégia de conteúdo para a presença da Arotec no LinkedIn - empresa com 50 anos de tradição, representando marcas como Struers, Foerster e Evident no Brasil. Focado na produção de conteúdo técnico e institucional adaptado ao público B2B. As responsabilidades incluíam a criação do calendário editorial, a redação de textos alinhados às tendências do setor e às inovações de produtos, a coordenação de materiais visuais com o designer e a garantia de que as aprovações do cliente seguissem os padrões de comunicação e a precisão técnica.",
            "proj8-title": "Zulcare",
            "proj8-role": "2024/25 - Freelancer",
            "proj8-desc": "Responsável pelo planejamento e produção de conteúdo para a Zulcare, uma loja e cozinha de doces artesanais. Criação do calendário editorial, redação de conteúdo que enfatizava ingredientes naturais e técnicas artesanais, e coordenação com o designer para a criação de peças visuais que capturassem o apelo sensorial e emocional da marca. Conduzir aprovações com o cliente para garantir mensagens consistentes e destaques sazonais.",
            "proj9-title": "Lig Veículos",
            "proj9-role": "2023/24/25 - Freelancer",
            "proj9-desc": "Desenvolvimento da estratégia de conteúdo de mídia social para a LigVeículos, uma empresa líder em vendas, aluguel e manutenção de veículos elétricos no Brasil. As responsabilidades incluiam a organização do calendário editorial, a criação de conteúdo educativo e promocional e a mediação entre o designer e o cliente durante as etapas de criação e aprovação. O objetivo era posicionar a marca como referência em mobilidade sustentável e inovadora.",
            "proj10-title": "Mesa III - Pastifício",
            "proj10-role": "2023/24 - Freelancer",
            "proj10-desc": "Responsável por estruturar o planejamento e a execução do conteúdo da Mesa3, uma loja de massas artesanais liderada pela chef Ana Soares. A função incluiu a elaboração do calendário editorial, a redação de conteúdo envolvente e centrado no produto e a coordenação de recursos visuais com o designer. Mantive contato próximo com o cliente para revisar e aprovar materiais criativos que destacavam a natureza artesanal e exclusiva da marca.",
            "proj11-title": "Ice4Pros",
            "proj11-role": "2023/24 - Freelancer",
            "proj11-desc": "Responsável por desenvolver e gerenciar a estratégia de conteúdo da Ice4Pros, uma marca que trouxe inovação ao mercado de coquetéis do Brasil por meio de gelo perfeitamente trabalhado, transparente e padronizado. As atividades incluíram o planejamento do calendário editorial, a redação de conteúdo para mídias sociais e a coordenação com o designer para a produção de ativos criativos. Atuei como ponte entre as entregas criativas e as aprovações do cliente, garantindo o alinhamento com o posicionamento da marca.",
            "proj12-title": "Kssara",
            "proj12-role": "2023 - Freelancer",
            "proj12-desc": "Liderei o desenvolvimento da estratégia de conteúdo de mídia social para o Emporio Kssara, um mercado gourmet do Oriente Médio em São Paulo que oferece nozes, produtos importados e bebidas. As tarefas envolviam a criação do calendário editorial, a redação de conteúdo focado no produto, a coordenação com o designer para a criação de artes visuais e aprovação com o cliente para garantir uma comunicação eficaz.",
            "proj13-title": "Carnes del Sur",
            "proj13-role": "2023 - Freelancer",
            "proj13-desc": "Responsável pelo planejamento e execução da estratégia de conteúdo da Carnes del Sur, um açougue especializado em cortes premium para churrascos e refeições diárias. As funções incluíam a criação do calendário editorial, a redação de postagens que se conectassem com amantes de carne e entusiastas de grelhados, o alinhamento de materiais criativos com o designer e a liderança do processo de aprovação com o cliente para manter alinhamento com a estratégia do negócio.",
            "proj14-title": "Amazon",
            "proj14-role": "Alexa Smart Home Table",
            "proj14-desc": "Conduzi o desenvolvimento e a implementação da nova mesa de exibição Alexa na Fast Shop, apresentando um modelo integrado de casa inteligente para aprimorar a narrativa do produto e o envolvimento do comprador. Gerenciamento de todo o processo, desde o briefing e o alinhamento criativo com a agência até a coordenação do fornecedor e a negociação com o varejo. O conceito apresentou um layout premium com iluminação ambiente, acabamentos naturais e uma demonstração imersiva de dispositivos conectados em um ambiente doméstico simulado.",
            "proj15-title": "Amazon",
            "proj15-role": "Echo Display Revamp",
            "proj15-desc": "Responsável pelo processo de ponta a ponta para a implementação de um novo conceito de display para os dispositivos Amazon Echo, desde o briefing e o alinhamento com a agência de criação até a coordenação de fornecedores e negociações com o varejo para a implementação na loja. O novo design proporcionou uma estética mais limpa, iluminação integrada, texturas naturais e melhor segmentação de produtos, resultando em uma experiência de compra mais premium e intuitiva.",
            "proj16-title": "Amazon",
            "proj16-role": "Alexa Table",
            "proj16-desc": "Coordenação da atualização da Amazon Table para aprimorar a experiência do comprador no ponto de venda. O projeto se concentrou na reorganização do layout do produto e na melhoria da comunicação visual para destacar os principais recursos e interações do ecossistema Alexa. Além disso, assegurei o alinhamento entre equipes internas, parceiros de varejo e fornecedores de produção para oferecer uma experiência limpa, intuitiva e consistente com a marca no PDV.",
            "proj17-title": "Ferrero",
            "proj17-role": "Kids Day",
            "proj17-desc": "Na campanha do Dia das Crianças, conduziu o desenvolvimento de materiais de PDV e ativações na loja, combinando as linhas de produtos Kinder e Nutella. A iniciativa incluiu a criação de displays temáticos - como o trem Kinder - e a coordenação com agências de criação e fornecedores para trazer visibilidade lúdica e de alto impacto para o ponto de venda. Administrou todo o processo, desde o briefing até o lançamento, reforçando a presença e o envolvimento da marca durante um período sazonal importante.",
            "proj18-title": "Ferrero",
            "proj18-role": "Nutella",
            "proj18-desc": "Apoio no desenvolvimento e a implementação do conceito Pão na Chapa com Nutella em padarias de todo o Brasil - inspirado na ideia de que “o café da manhã brasileiro fora de casa é pão na chapa... então por que não com Nutella?” . Supervisão da criação de materiais promocionais para a comunicação na loja e coordenação de ativações locais de degustação para aumentar a visibilidade, a experimentação e a adoção da iniciativa.",
            "proj19-title": "Ferrero",
            "proj19-role": "Visibility",
            "proj19-desc": "Suporte ao desenvolvimento de materiais importantes para a campanha de Páscoa, incluindo displays de PDV, catálogos de produtos e guias de execução. Acompanhamento da produção, monitoramento das entregas e organização da distribuição de materiais para a equipe de merchandising para garantir a implementação adequada no ponto de venda.",
            "proj20-title": "Mead Johnson",
            "proj20-role": "Sustagen Nutriferro Farma Launch",
            "proj20-desc": "Participação no lançamento do Sustagem Nutriferro desenvolvendo e negociando a instalação de frigobares da marca em drogarias selecionadas - um recurso incomum nesse ambiente de varejo. A iniciativa visava oferecer o produto refrigerado para consumo em qualquer lugar, aumentando a visibilidade e exigindo uma coordenação estreita com as equipes comerciais e as redes de varejo.",
            "proj21-title": "Mead Johnson",
            "proj21-role": "Sustagen Category",
            "proj21-desc": "Desenvolvimento de uma unidade de exibição personalizada (formato de ilha) para melhorar a presença do Sustagen nos supermercados. O projeto se concentrou na criação de um novo formato de material de PDV para melhorar a visibilidade do produto, facilitar o reabastecimento e atrair a atenção do consumidor no ponto de venda. Envolveu o planejamento de materiais, o alinhamento com os fornecedores e a coordenação com as equipes comerciais para garantir o lançamento nas principais lojas de alto tráfego.",
            "proj22-title": "Mead Johnson",
            "proj22-role": "Sustagen Category",
            "proj22-desc": "Coordenação do desenvolvimento de materiais de ponto de venda para o lançamento do Sustagen Nutriferro. Responsável pelo processo de briefing e trabalho em conjunto com agências de criação no projeto de um kit completo de PDV, com o objetivo de aumentar a visibilidade e a conversão. Gerenciamento do alinhamento da produção com os fornecedores para garantir a qualidade da execução e a entrega pontual aos principais parceiros varejistas.",
        }
    }
};


function setLanguage(lang) {
    const langData = translations[lang];

    document.querySelectorAll("[id]").forEach(el => {
        const key = el.id;

        // procurar em todas as categorias
        for (const section in langData) {
            if (langData[section][key]) {
                el.textContent = langData[section][key];
                break;
            }
        }
    });

    localStorage.setItem("lang", lang);
}